# Generated by Django 5.2 on 2026-07-01 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_product_download_label'),
        ('licensing', '0010_vendorlicensepool_unique_vendor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensekey',
            name='source',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('vendor', 'Vendor'), ('trial', 'Trial')], default='stripe', max_length=10),
        ),
        migrations.CreateModel(
            name='TrialClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id_hash', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_claim', to='licensing.licensekey')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_claims', to='billing.product')),
            ],
            options={
                'unique_together': {('product', 'machine_id_hash')},
            },
        ),
    ]
