#!/usr/bin/env python3
"""
install.py -- module lifecycle manager
Usage:
    python install.py add <module_name>
    python install.py remove <module_name>
    python install.py regen

Must be run with the project venv activated (same requirement as manage.py).
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT_DIR     = Path(__file__).resolve().parent
MODULES_DIR  = ROOT_DIR / "modules"
BACKEND_DIR  = ROOT_DIR / "core" / "backend"
FRONTEND_DIR = ROOT_DIR / "core" / "frontend"
MANIFEST     = FRONTEND_DIR / "src" / "modules.js"
MANAGE_PY    = BACKEND_DIR / "manage.py"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _run(*cmd, cwd=None):
    """Run a subprocess command; exit with a clear message on failure."""
    result = subprocess.run(cmd, cwd=cwd)
    if result.returncode != 0:
        _die(f"Command failed (exit {result.returncode}): {' '.join(str(c) for c in cmd)}")


def _npm():
    """Return the npm executable path. Handles npm.cmd on Windows."""
    npm = shutil.which("npm")
    if not npm:
        _die("npm not found in PATH. Install Node.js and ensure npm is on PATH.")
    return npm


def _load_module_json(module_dir):
    """Load and return the parsed module.json for a module directory."""
    path = module_dir / "module.json"
    assert path.exists(), f"module.json missing in {module_dir}"
    with path.open() as f:
        return json.load(f)


def _topo_sort(graph):
    """Topological sort of module names so dependencies precede dependents.

    graph: dict mapping module_name -> list of required module names.
    Raises ValueError on circular dependency.
    """
    from collections import deque

    installed = set(graph)
    in_degree = {name: 0 for name in installed}
    dependents = {name: [] for name in installed}

    for name, requires in graph.items():
        for req in requires:
            if req in installed:
                in_degree[name] += 1
                dependents[req].append(name)

    queue = deque(sorted(n for n in installed if in_degree[n] == 0))
    result = []
    while queue:
        node = queue.popleft()
        result.append(node)
        for dep in sorted(dependents[node]):
            in_degree[dep] -= 1
            if in_degree[dep] == 0:
                queue.append(dep)

    if len(result) != len(installed):
        cycle = sorted(n for n in installed if n not in result)
        raise ValueError(f"Circular dependency detected among modules: {cycle}")

    return result


# ---------------------------------------------------------------------------
# Manifest generation
# ---------------------------------------------------------------------------

def generate_manifest(exclude=None):
    """Rewrite core/frontend/src/modules.js from the current modules/ state.

    exclude: module name to omit from the manifest (used during 'remove'
             before the directory has been deleted).

    Uses `import * as <name>Module` so that optional exports (providers,
    navItems) can be absent from a module without causing a static import
    error. Missing exports resolve to undefined and are guarded with ?? [].
    """
    imports, route_items, nav_items, provider_items = [], [], [], []

    for module_dir in sorted(MODULES_DIR.iterdir()):
        if not module_dir.is_dir():
            continue
        name = module_dir.name
        if name == exclude:
            continue
        if not (module_dir / "module.json").exists():
            continue
        imports.append(f"import * as {name}Module from '@modules/{name}';")
        route_items.append(f"  ...({name}Module.routes ?? []),")
        nav_items.append(f"  ...({name}Module.navItems ?? []),")
        provider_items.append(f"  ...({name}Module.providers ?? []),")

    lines = ["// Generated by install.py -- do not edit by hand."]
    if imports:
        lines.append("")
        lines.extend(imports)
    lines += [
        "",
        "export const moduleRoutes = [",
        *route_items,
        "];",
        "",
        "export const moduleNavItems = [",
        *nav_items,
        "];",
        "",
        "export const moduleProviders = [",
        *provider_items,
        "];",
        "",  # trailing newline
    ]

    MANIFEST.write_text("\n".join(lines))
    print(f"  + Regenerated {MANIFEST.relative_to(ROOT_DIR)}")


# ---------------------------------------------------------------------------
# installed_modules.py generation
# ---------------------------------------------------------------------------

def generate_installed_modules(exclude=None):
    """Write backend/core/installed_modules.py from the current modules/ state.

    exclude: module name to omit (used during 'remove').
    """
    graph = {}
    extra_apps_map = {}
    extra_mw_map = {}
    settings_map = {}

    for entry in sorted(MODULES_DIR.iterdir()):
        if not entry.is_dir():
            continue
        if not (entry / "module.json").exists():
            continue
        name = entry.name
        if name == exclude:
            continue

        data = _load_module_json(entry)
        graph[name] = data.get("requires", [])
        extra_apps_map[name] = data.get("django_apps", [])
        extra_mw_map[name] = data.get("middleware", [])
        settings_map[name] = data.get("settings_defaults", {})

    ordered = _topo_sort(graph)

    seen_apps = set()
    extra_apps = []
    for name in ordered:
        for app in extra_apps_map.get(name, []):
            if app not in seen_apps:
                seen_apps.add(app)
                extra_apps.append(app)

    seen_mw = set()
    extra_middleware = []
    for name in ordered:
        for mw in extra_mw_map.get(name, []):
            if mw not in seen_mw:
                seen_mw.add(mw)
                extra_middleware.append(mw)

    settings_defaults = {}
    for name in ordered:
        for key, value in settings_map.get(name, {}).items():
            if key not in settings_defaults:
                settings_defaults[key] = value

    out = BACKEND_DIR / "core" / "installed_modules.py"
    lines = [
        "# Generated by install.py — do not edit by hand.",
        f"INSTALLED_MODULE_APPS   = {ordered!r}",
        f"MODULE_EXTRA_APPS       = {extra_apps!r}",
        f"MODULE_EXTRA_MIDDLEWARE = {extra_middleware!r}",
        f"MODULE_SETTINGS         = {settings_defaults!r}",
        "",
    ]
    out.write_text("\n".join(lines))
    print(f"  + Regenerated {out.relative_to(ROOT_DIR)}")


# ---------------------------------------------------------------------------
# Add
# ---------------------------------------------------------------------------

def add(name):
    module_dir = MODULES_DIR / name
    if not module_dir.is_dir():
        _die(f"modules/{name} not found.")
    if not (module_dir / "module.json").exists():
        _die(f"modules/{name}/module.json missing.")

    manifest = _load_module_json(module_dir)
    print(f"Installing module: {name}")

    # Verify declared dependencies are present
    for dep in manifest.get("requires", []):
        if not (MODULES_DIR / dep).is_dir():
            _die(f"'{name}' requires module '{dep}' which is not installed.")
        print(f"  + Dependency '{dep}' present")

    # Python dependencies — prefer pip_packages in module.json, fall back to requirements.txt
    pip_packages = manifest.get("pip_packages", [])
    if pip_packages:
        print("  Installing Python packages...")
        _run(sys.executable, "-m", "pip", "install", *pip_packages, "-q")
    else:
        req_file = module_dir / "backend" / "requirements.txt"
        if req_file.exists() and req_file.stat().st_size > 0:
            print("  Installing Python packages...")
            _run(sys.executable, "-m", "pip", "install", "-r", str(req_file), "-q")

    # Backend symlink: core/backend/<name> -> ../../modules/<name>/backend/<name>
    app_src = MODULES_DIR / name / "backend" / name
    if not app_src.exists():
        _die(f"Django app directory not found: {app_src}")
    backend_link = BACKEND_DIR / name
    if not backend_link.exists():
        target = Path("../../modules") / name / "backend" / name
        backend_link.symlink_to(target)
        print(f"  + Created symlink core/backend/{name} -> {target}")

    # Frontend symlink: core/frontend/modules/<name> -> ../../../modules/<name>/frontend
    (FRONTEND_DIR / "modules").mkdir(exist_ok=True)
    frontend_link = FRONTEND_DIR / "modules" / name
    if not frontend_link.exists():
        target = Path("../../../modules") / name / "frontend"
        frontend_link.symlink_to(target)
        print(f"  + Created symlink core/frontend/modules/{name} -> {target}")

    # Regenerate manifests
    generate_manifest()
    generate_installed_modules()

    # npm install (picks up new workspace entry via symlink)
    print("  Installing frontend packages...")
    _run(_npm(), "install", cwd=FRONTEND_DIR)

    # Django migrations
    print("  Running migrations...")
    _run(sys.executable, str(MANAGE_PY), "migrate")

    # Remind about any manual settings that can't be automated
    settings_doc = module_dir / "backend" / manifest.get("django_app", name) / "module_settings.py"
    if settings_doc.exists():
        print(f"\nNOTE: {settings_doc.relative_to(ROOT_DIR)} contains additional settings")
        print("  Review that file and merge any required values into core/backend/core/settings/.")

    print(f"\nDone. Module '{name}' installed.")


# ---------------------------------------------------------------------------
# Remove
# ---------------------------------------------------------------------------

def remove(name):
    module_dir = MODULES_DIR / name
    if not module_dir.is_dir():
        _die(f"modules/{name} not found.")

    print(f"Removing module: {name}")

    # Block removal if another installed module depends on this one
    for other_dir in sorted(MODULES_DIR.iterdir()):
        if not other_dir.is_dir() or other_dir.name == name:
            continue
        if not (other_dir / "module.json").exists():
            continue
        other = _load_module_json(other_dir)
        if name in other.get("requires", []):
            _die(f"Cannot remove '{name}' -- module '{other_dir.name}' depends on it.")

    # Regenerate manifests excluding this module
    generate_manifest(exclude=name)
    generate_installed_modules(exclude=name)

    # Remove backend symlink
    backend_link = BACKEND_DIR / name
    if backend_link.is_symlink():
        backend_link.unlink()
        print(f"  - Removed symlink core/backend/{name}")

    # Remove frontend symlink
    frontend_link = FRONTEND_DIR / "modules" / name
    if frontend_link.is_symlink():
        frontend_link.unlink()
        print(f"  - Removed symlink core/frontend/modules/{name}")

    print(f"Done. Module '{name}' removed.")
    print("NOTE: Run migrations manually to roll back any database changes.")
    print(f"NOTE: Delete modules/{name} (and its git submodule entry) when ready.")


# ---------------------------------------------------------------------------
# Regen
# ---------------------------------------------------------------------------

def regen():
    """Regenerate installed_modules.py and modules.js from current modules/ state."""
    print("Regenerating manifests...")
    generate_manifest()
    generate_installed_modules()
    print("Done.")


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

COMMANDS = {"add": add, "remove": remove, "regen": regen}


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in COMMANDS:
        print("Usage: python install.py add|remove <module_name>", file=sys.stderr)
        print("       python install.py regen", file=sys.stderr)
        sys.exit(1)
    cmd = sys.argv[1]
    if cmd == "regen":
        regen()
    elif len(sys.argv) != 3:
        print(f"Usage: python install.py {cmd} <module_name>", file=sys.stderr)
        sys.exit(1)
    else:
        COMMANDS[cmd](sys.argv[2])


if __name__ == "__main__":
    main()
