#!/usr/bin/env python3
"""
install.py -- module lifecycle manager
Usage:
    python install.py add <module_name>
    python install.py remove <module_name>

Must be run with the project venv activated (same requirement as manage.py).
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT_DIR     = Path(__file__).resolve().parent
MODULES_DIR  = ROOT_DIR / "modules"
BACKEND_DIR  = ROOT_DIR / "core" / "backend"
FRONTEND_DIR = ROOT_DIR / "core" / "frontend"
MANIFEST     = FRONTEND_DIR / "src" / "modules.js"
MANAGE_PY    = BACKEND_DIR / "manage.py"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def _run(*cmd, cwd=None):
    """Run a subprocess command; exit with a clear message on failure."""
    result = subprocess.run(cmd, cwd=cwd)
    if result.returncode != 0:
        _die(f"Command failed (exit {result.returncode}): {' '.join(str(c) for c in cmd)}")


def _npm():
    """Return the npm executable path. Handles npm.cmd on Windows."""
    npm = shutil.which("npm")
    if not npm:
        _die("npm not found in PATH. Install Node.js and ensure npm is on PATH.")
    return npm


def _load_module_json(module_dir):
    """Load and return the parsed module.json for a module directory."""
    path = module_dir / "module.json"
    assert path.exists(), f"module.json missing in {module_dir}"
    with path.open() as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Manifest generation
# ---------------------------------------------------------------------------

def generate_manifest(exclude=None):
    """Rewrite core/frontend/src/modules.js from the current modules/ state.

    exclude: module name to omit from the manifest (used during 'remove'
             before the directory has been deleted).

    Uses `import * as <name>Module` so that optional exports (providers,
    navItems) can be absent from a module without causing a static import
    error. Missing exports resolve to undefined and are guarded with ?? [].
    """
    imports, route_items, nav_items, provider_items = [], [], [], []

    for module_dir in sorted(MODULES_DIR.iterdir()):
        if not module_dir.is_dir():
            continue
        name = module_dir.name
        if name == exclude:
            continue
        if not (module_dir / "module.json").exists():
            continue
        imports.append(f"import * as {name}Module from '@modules/{name}';")
        route_items.append(f"  ...({name}Module.routes ?? []),")
        nav_items.append(f"  ...({name}Module.navItems ?? []),")
        provider_items.append(f"  ...({name}Module.providers ?? []),")

    lines = ["// Generated by install.py -- do not edit by hand."]
    if imports:
        lines.append("")
        lines.extend(imports)
    lines += [
        "",
        "export const moduleRoutes = [",
        *route_items,
        "];",
        "",
        "export const moduleNavItems = [",
        *nav_items,
        "];",
        "",
        "export const moduleProviders = [",
        *provider_items,
        "];",
        "",  # trailing newline
    ]

    MANIFEST.write_text("\n".join(lines))
    print(f"  + Regenerated {MANIFEST.relative_to(ROOT_DIR)}")


# ---------------------------------------------------------------------------
# Add
# ---------------------------------------------------------------------------

def add(name):
    module_dir = MODULES_DIR / name
    if not module_dir.is_dir():
        _die(f"modules/{name} not found.")
    if not (module_dir / "module.json").exists():
        _die(f"modules/{name}/module.json missing.")

    manifest = _load_module_json(module_dir)
    print(f"Installing module: {name}")

    # Verify declared dependencies are present
    for dep in manifest.get("requires", []):
        if not (MODULES_DIR / dep).is_dir():
            _die(f"'{name}' requires module '{dep}' which is not installed.")
        print(f"  + Dependency '{dep}' present")

    # Python dependencies
    req_file = module_dir / "backend" / "requirements.txt"
    if req_file.exists() and req_file.stat().st_size > 0:
        print("  Installing Python packages...")
        _run(sys.executable, "-m", "pip", "install", "-r", str(req_file), "-q")

    # Django migrations
    print("  Running migrations...")
    _run(sys.executable, str(MANAGE_PY), "migrate")

    # Frontend packages (npm workspaces links the new module automatically)
    print("  Installing frontend packages...")
    _run(_npm(), "install", "--silent", cwd=FRONTEND_DIR)

    # Regenerate the frontend route manifest
    generate_manifest()

    print(f"Done. Module '{name}' installed.")


# ---------------------------------------------------------------------------
# Remove
# ---------------------------------------------------------------------------

def remove(name):
    module_dir = MODULES_DIR / name
    if not module_dir.is_dir():
        _die(f"modules/{name} not found.")

    print(f"Removing module: {name}")

    # Block removal if another installed module depends on this one
    for other_dir in sorted(MODULES_DIR.iterdir()):
        if not other_dir.is_dir() or other_dir.name == name:
            continue
        if not (other_dir / "module.json").exists():
            continue
        other = _load_module_json(other_dir)
        if name in other.get("requires", []):
            _die(f"Cannot remove '{name}' -- module '{other_dir.name}' depends on it.")

    # Regenerate manifest now, excluding this module
    generate_manifest(exclude=name)

    print(f"Done. Module '{name}' removed from manifest.")
    print("NOTE: Run migrations manually to roll back any database changes.")
    print(f"NOTE: Delete modules/{name} (and its git submodule entry) when ready.")


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

COMMANDS = {"add": add, "remove": remove}


def main():
    if len(sys.argv) != 3 or sys.argv[1] not in COMMANDS:
        print("Usage: python install.py add|remove <module_name>", file=sys.stderr)
        sys.exit(1)
    COMMANDS[sys.argv[1]](sys.argv[2])


if __name__ == "__main__":
    main()
