#!/usr/bin/env bash
# install.sh — module lifecycle manager
# Usage: bash install.sh add <module_name>
#        bash install.sh remove <module_name>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULES_DIR="$SCRIPT_DIR/modules"
BACKEND_DIR="$SCRIPT_DIR/core/backend"
FRONTEND_DIR="$SCRIPT_DIR/core/frontend"
MANIFEST_FILE="$FRONTEND_DIR/src/modules.js"

# ---------------------------------------------------------------------------
# Venv activation — handles Windows (Git Bash) and Linux/Mac (CI + production)
# ---------------------------------------------------------------------------
_activate_venv() {
  local venv_dir="$SCRIPT_DIR/venv"
  if [[ ! -d "$venv_dir" ]]; then
    echo "ERROR: venv not found at $venv_dir. Create it with: python -m venv venv" >&2
    exit 1
  fi
  if [[ -f "$venv_dir/Scripts/activate" ]]; then
    # shellcheck disable=SC1091
    source "$venv_dir/Scripts/activate"
  else
    # shellcheck disable=SC1091
    source "$venv_dir/bin/activate"
  fi
}

# ---------------------------------------------------------------------------
# Manifest regeneration — rewrites core/frontend/src/modules.js
# ---------------------------------------------------------------------------
_generate_manifest() {
  local imports="" route_items="" nav_items=""

  for module_dir in "$MODULES_DIR"/*/; do
    [[ -d "$module_dir" ]] || continue
    local name
    name=$(basename "$module_dir")
    local manifest="$module_dir/module.json"
    [[ -f "$manifest" ]] || continue

    imports+="import { routes as ${name}Routes, navItems as ${name}Nav } from '@modules/${name}';"$'\n'
    route_items+="  ...${name}Routes,"$'\n'
    nav_items+="  ...${name}Nav,"$'\n'
  done

  cat > "$MANIFEST_FILE" <<EOF
// Generated by install.sh — do not edit by hand.
${imports}
export const moduleRoutes = [
${route_items}];

export const moduleNavItems = [
${nav_items}];
EOF

  echo "  ✓ Regenerated $MANIFEST_FILE"
}

# ---------------------------------------------------------------------------
# Add a module
# ---------------------------------------------------------------------------
_add() {
  local name="$1"
  local module_dir="$MODULES_DIR/$name"

  [[ -d "$module_dir" ]] || { echo "ERROR: modules/$name not found." >&2; exit 1; }
  [[ -f "$module_dir/module.json" ]] || { echo "ERROR: modules/$name/module.json missing." >&2; exit 1; }

  echo "Installing module: $name"

  # Check required dependencies
  local requires
  requires=$(python3 -c "import json,sys; d=json.load(open('$module_dir/module.json')); print(' '.join(d.get('requires',[])))" 2>/dev/null || true)
  for dep in $requires; do
    [[ -d "$MODULES_DIR/$dep" ]] || {
      echo "ERROR: $name requires module '$dep' which is not installed." >&2
      exit 1
    }
    echo "  ✓ Dependency '$dep' present"
  done

  _activate_venv

  # Install backend dependencies
  local req_file="$module_dir/backend/requirements.txt"
  if [[ -f "$req_file" ]] && [[ -s "$req_file" ]]; then
    echo "  Installing Python packages..."
    pip install -r "$req_file" --quiet
  fi

  # Run migrations
  echo "  Running migrations..."
  python "$BACKEND_DIR/manage.py" migrate

  # Install frontend dependencies
  echo "  Installing frontend packages..."
  npm install --prefix "$FRONTEND_DIR" --quiet

  # Regenerate manifest
  _generate_manifest

  echo "Done. Module '$name' installed."
}

# ---------------------------------------------------------------------------
# Remove a module
# ---------------------------------------------------------------------------
_remove() {
  local name="$1"
  local module_dir="$MODULES_DIR/$name"

  [[ -d "$module_dir" ]] || { echo "ERROR: modules/$name not found." >&2; exit 1; }

  echo "Removing module: $name"

  # Check nothing else depends on this module
  for other_dir in "$MODULES_DIR"/*/; do
    local other
    other=$(basename "$other_dir")
    [[ "$other" == "$name" ]] && continue
    local other_manifest="$other_dir/module.json"
    [[ -f "$other_manifest" ]] || continue
    local deps
    deps=$(python3 -c "import json; d=json.load(open('$other_manifest')); print(' '.join(d.get('requires',[])))" 2>/dev/null || true)
    for dep in $deps; do
      if [[ "$dep" == "$name" ]]; then
        echo "ERROR: Cannot remove '$name' — module '$other' depends on it." >&2
        exit 1
      fi
    done
  done

  # Regenerate manifest (module dir still present but excluded by convention;
  # caller should git submodule deinit / remove the directory afterward)
  _generate_manifest

  echo "Done. Module '$name' removed from manifest."
  echo "NOTE: Run migrations manually if you need to roll back database changes."
  echo "NOTE: Remove the modules/$name directory (and git submodule entry) when ready."
}

# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------
ACTION="${1:-}"
MODULE="${2:-}"

case "$ACTION" in
  add)
    [[ -n "$MODULE" ]] || { echo "Usage: bash install.sh add <module_name>" >&2; exit 1; }
    _add "$MODULE"
    ;;
  remove)
    [[ -n "$MODULE" ]] || { echo "Usage: bash install.sh remove <module_name>" >&2; exit 1; }
    _remove "$MODULE"
    ;;
  *)
    echo "Usage: bash install.sh add|remove <module_name>" >&2
    exit 1
    ;;
esac
