// Generated by install.py -- do not edit by hand.

import * as helloworldModule from '@modules/helloworld';
import * as userauthModule from '@modules/userauth';

export const moduleRoutes = [
  ...(helloworldModule.routes ?? []),
  ...(userauthModule.routes ?? []),
];

export const moduleNavItems = [
  ...(helloworldModule.navItems ?? []),
  ...(userauthModule.navItems ?? []),
];

export const moduleProviders = [
  ...(helloworldModule.providers ?? []),
  ...(userauthModule.providers ?? []),
];
