// Generated by install.py -- do not edit by hand.

import * as billingModule from '@modules/billing';
import * as fileuploadModule from '@modules/fileupload';
import * as licensingModule from '@modules/licensing';
import * as orgsModule from '@modules/orgs';
import * as supportModule from '@modules/support';
import * as userauthModule from '@modules/userauth';

export const moduleRoutes = [
  ...(billingModule.routes ?? []),
  ...(fileuploadModule.routes ?? []),
  ...(licensingModule.routes ?? []),
  ...(orgsModule.routes ?? []),
  ...(supportModule.routes ?? []),
  ...(userauthModule.routes ?? []),
];

export const moduleNavItems = [
  ...(billingModule.navItems ?? []),
  ...(fileuploadModule.navItems ?? []),
  ...(licensingModule.navItems ?? []),
  ...(orgsModule.navItems ?? []),
  ...(supportModule.navItems ?? []),
  ...(userauthModule.navItems ?? []),
];

export const moduleProviders = [
  ...(billingModule.providers ?? []),
  ...(fileuploadModule.providers ?? []),
  ...(licensingModule.providers ?? []),
  ...(orgsModule.providers ?? []),
  ...(supportModule.providers ?? []),
  ...(userauthModule.providers ?? []),
];

export const moduleNavbarEnd = [
  ...(billingModule.navbarEnd ?? []),
  ...(fileuploadModule.navbarEnd ?? []),
  ...(licensingModule.navbarEnd ?? []),
  ...(orgsModule.navbarEnd ?? []),
  ...(supportModule.navbarEnd ?? []),
  ...(userauthModule.navbarEnd ?? []),
];

export const moduleAdminCards = [
  ...(billingModule.adminCards ?? []),
  ...(fileuploadModule.adminCards ?? []),
  ...(licensingModule.adminCards ?? []),
  ...(orgsModule.adminCards ?? []),
  ...(supportModule.adminCards ?? []),
  ...(userauthModule.adminCards ?? []),
];

export const moduleUserSections = [
  ...(billingModule.userSections ?? []),
  ...(fileuploadModule.userSections ?? []),
  ...(licensingModule.userSections ?? []),
  ...(orgsModule.userSections ?? []),
  ...(supportModule.userSections ?? []),
  ...(userauthModule.userSections ?? []),
];

export const moduleHomeSections = [
  ...(billingModule.homeSections ?? []),
  ...(fileuploadModule.homeSections ?? []),
  ...(licensingModule.homeSections ?? []),
  ...(orgsModule.homeSections ?? []),
  ...(supportModule.homeSections ?? []),
  ...(userauthModule.homeSections ?? []),
];
