// Generated by install.py -- do not edit by hand.

import { routes as helloworldRoutes, navItems as helloworldNav } from '@modules/helloworld';
import { routes as userauthRoutes, navItems as userauthNav } from '@modules/userauth';

export const moduleRoutes = [
  ...helloworldRoutes,
  ...userauthRoutes,
];

export const moduleNavItems = [
  ...helloworldNav,
  ...userauthNav,
];
