/**
 * index.js — Public API for the userauth module.
 *
 * Consumed by core/frontend/src/modules.js (generated by install.py).
 *
 * Required exports (consumed by install.py / core shell)
 * ───────────────────────────────────────────────────────
 * routes    — React Router route definitions
 * navItems  — Navbar entries (empty; auth UI is driven by AuthContext)
 * providers — Provider components wrapping the app tree (AuthProvider)
 *
 * Public exports for other modules
 * ─────────────────────────────────
 * useAuth      — access auth state (user, login, logout, isLoading)
 * AuthProvider — in case a module needs to mount it manually
 * authApi      — call auth endpoints (login, register, refresh, etc.)
 * AuthCard     — card wrapper shared by auth-style pages in other modules
 * FormField    — labelled input with icon and error, used across auth forms
 * GoogleButton — Google OAuth button, reusable in any signup/login flow
 * NavbarEnd    — right-side navbar slot (login/logout button)
 */

import './components/auth.css'

export { routes, navItems } from './routes.jsx'

export { AuthProvider, useAuth } from './context/AuthContext'
export { authApi }               from './api'
export { default as AuthCard }   from './components/AuthCard'
export { default as FormField }  from './components/FormField'
export { default as GoogleButton } from './components/GoogleButton'
export { default as NavbarEnd }  from './components/NavbarEnd'

// Provider list for core/main.jsx ModuleProviders wrapper.
import { AuthProvider } from './context/AuthContext'
export const providers = [AuthProvider]
