/**
 * index.js — Public API for the userauth module.
 *
 * Consumed by core/frontend/src/modules.js (generated by install.py).
 *
 * Exports
 * ───────
 * routes    — React Router route definitions (see routes.jsx)
 * navItems  — Navbar link entries (empty — auth handled via AuthContext)
 * providers — React provider components that must wrap the app tree.
 *             AuthProvider is included so all routes have access to useAuth().
 *
 * Direct consumer imports
 * ───────────────────────
 * import { useAuth } from '@modules/userauth'
 * import { AuthProvider } from '@modules/userauth'
 */

export { routes, navItems } from './routes.jsx'

// AuthProvider must wrap the whole app — registered in core via moduleProviders.
export { AuthProvider, useAuth } from './modules/auth/context/AuthContext'

// Re-export public auth API for use by other modules.
export { authApi }         from './modules/auth/auth_api'
export { useRecaptcha }    from './modules/auth/hooks/useRecaptcha'
export { default as AuthCard }        from './modules/auth/components/AuthCard'
export { default as FormField }       from './modules/auth/components/FormField'
export { default as GoogleButton }    from './modules/auth/components/GoogleButton'
export { default as StepIndicator }   from './modules/auth/components/StepIndicator'
export { default as EmailVerifyForm } from './modules/auth/components/EmailVerifyForm'

// Provider list for core/main.jsx ModuleProviders wrapper.
import { AuthProvider } from './modules/auth/context/AuthContext'
import GoogleProvider from './modules/auth/context/GoogleProvider'
export const providers = [GoogleProvider, AuthProvider]

// Navbar right-side slot — rendered in core Navbar's navbar-end.
export { default as NavbarEnd } from './modules/auth/components/NavbarEnd'
