/**
 * routes.jsx — Auth module route definitions.
 *
 * Consumed by core/frontend/src/modules.js (generated by install.py).
 * Export `routes` for React Router and `navItems` for the Navbar.
 *
 * Auth nav links are intentionally absent from navItems — the Navbar renders
 * Login/Logout conditionally based on AuthContext state, not nav list entries.
 */

import Login          from './modules/auth/pages/Login'
import Signup         from './modules/auth/pages/Signup'
import ForgotPassword from './modules/auth/pages/ForgotPassword'
import ResetPassword  from './modules/auth/pages/ResetPassword'
import VerifyEmail    from './modules/auth/pages/VerifyEmail'

export const routes = [
  { path: '/login',                  element: <Login /> },
  { path: '/signup',                 element: <Signup /> },
  { path: '/forgot-password',        element: <ForgotPassword /> },
  { path: '/reset-password/:token',  element: <ResetPassword /> },
  { path: '/verify-email/:token',    element: <VerifyEmail /> },
]

// No persistent nav links — auth UI is driven by Navbar checking AuthContext.
export const navItems = []
