/**
 * routes.jsx — Auth module route definitions.
 *
 * Consumed by core/frontend/src/modules.js (generated by install.py).
 * Export `routes` for React Router and `navItems` for the Navbar.
 *
 * Auth nav links are intentionally absent from navItems — the Navbar renders
 * Login/Logout conditionally based on AuthContext state, not nav list entries.
 */

import Login          from './pages/Login'
import Signup         from './pages/Signup'
import ForgotPassword from './pages/ForgotPassword'
import ResetPassword  from './pages/ResetPassword'
import VerifyEmail    from './pages/VerifyEmail'

export const routes = [
  { path: '/login',                  element: <Login /> },
  { path: '/signup',                 element: <Signup /> },
  { path: '/forgot-password',        element: <ForgotPassword /> },
  { path: '/reset-password/:token',  element: <ResetPassword /> },
  { path: '/verify-email/:token',    element: <VerifyEmail /> },
]

export const navItems = [
  { label: 'Dashboard',   path: '/dashboard' },
];
