# Generated by Django 5.2 on 2026-06-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_subscription_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensekey',
            options={'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
    ]
