// Generated by install.py -- do not edit by hand.

import { routes as billingRoutes, navItems as billingNav } from '@modules/billing';
import { routes as fileuploadRoutes, navItems as fileuploadNav } from '@modules/fileupload';
import { routes as helloworldRoutes, navItems as helloworldNav } from '@modules/helloworld';
import { routes as userauthRoutes, navItems as userauthNav, providers as userauthProviders, NavbarEnd as userauthNavbarEnd } from '@modules/userauth';

export const moduleRoutes = [
  ...billingRoutes,
  ...fileuploadRoutes,
  ...helloworldRoutes,
  ...userauthRoutes,
];

export const moduleNavItems = [
  ...billingNav,
  ...fileuploadNav,
  ...helloworldNav,
  ...userauthNav,
];

export const moduleProviders = [
  ...userauthProviders,
];

export const moduleNavbarEnd = [
  userauthNavbarEnd,
];
