# Generated by install.py — do not edit by hand.
import os
INSTALLED_MODULE_APPS   = ['billing', 'fileupload', 'userauth', 'orgs', 'support']
MODULE_EXTRA_APPS       = ['django.contrib.sites', 'allauth', 'allauth.account', 'allauth.socialaccount', 'allauth.socialaccount.providers.google', 'rest_framework.authtoken', 'dj_rest_auth', 'dj_rest_auth.registration', 'rest_framework_simplejwt']
MODULE_EXTRA_MIDDLEWARE = ['allauth.account.middleware.AccountMiddleware']
MODULE_SETTINGS         = {
    'STRIPE_SECRET_KEY': os.environ.get('STRIPE_SECRET_KEY', ''),
    'STRIPE_PUBLISHABLE_KEY': os.environ.get('STRIPE_PUBLISHABLE_KEY', ''),
    'STRIPE_WEBHOOK_SECRET': os.environ.get('STRIPE_WEBHOOK_SECRET', ''),
    'STRIPE_SUCCESS_URL': os.environ.get('STRIPE_SUCCESS_URL', ''),
    'STRIPE_CANCEL_URL': os.environ.get('STRIPE_CANCEL_URL', ''),
    'LICENSE_APP_SECRET': os.environ.get('LICENSE_APP_SECRET', ''),
    'LICENSE_RSA_PRIVATE_KEY_PATH': os.environ.get('LICENSE_RSA_PRIVATE_KEY_PATH', ''),
    'LICENSE_RSA_PUBLIC_KEY_PATH': os.environ.get('LICENSE_RSA_PUBLIC_KEY_PATH', ''),
    'LICENSE_DEFAULT_MAX_MACHINES': 1,
    'LICENSE_DEFAULT_OFFLINE_TTL_DAYS': 30,
    'AWS_FILEUPLOAD_ACCESS_KEY': os.environ.get('AWS_FILEUPLOAD_ACCESS_KEY', ''),
    'AWS_FILEUPLOAD_SECRET_KEY': os.environ.get('AWS_FILEUPLOAD_SECRET_KEY', ''),
    'AWS_FILEUPLOAD_S3_REGION': os.environ.get('AWS_FILEUPLOAD_S3_REGION', ''),
    'AWS_UPLOAD_BUCKET': os.environ.get('AWS_UPLOAD_BUCKET', ''),
    'AWS_PROCESSED_BUCKET': os.environ.get('AWS_PROCESSED_BUCKET', ''),
    'AWS_S3_REGION': 'us-east-1',
    'FILEUPLOAD_WEBHOOK_SECRET': os.environ.get('FILEUPLOAD_WEBHOOK_SECRET', ''),
    'SITE_ID': 1,
    'FRONTEND_URL': 'http://localhost:5173',
    'ACCOUNT_LOGIN_METHODS': {'username': True},
    'ACCOUNT_SIGNUP_FIELDS': ['email*', 'username*', 'password1*', 'password2*'],
    'ACCOUNT_EMAIL_VERIFICATION': 'none',
    'REST_AUTH': {'USE_JWT': True, 'JWT_AUTH_COOKIE': None, 'TOKEN_MODEL': None},
    'EMAIL_BACKEND': 'django_ses.SESBackend',
    'RECAPTCHA_SITE_KEY': os.environ.get('RECAPTCHA_SITE_KEY', ''),
    'RECAPTCHA_SECRET_KEY': os.environ.get('RECAPTCHA_SECRET_KEY', ''),
    'RECAPTCHA_PROJECT_ID': os.environ.get('RECAPTCHA_PROJECT_ID', ''),
    'RECAPTCHA_THRESHOLD': 0.5,
}
